### ISSUE TITLE
SSKW - Design doctor workflow through the app

### ISSUE THREAD

**Issue by omarefg** [Sphinx-Society/kaizen-web-client#34]
## Checklist ✅

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/Sphinx-Society/kaizen-backend) of this repository and believe that this is not a duplicate.

## Summary 💡

This views will allow the development team to know what to develop following the design system.

## Requirements 🌈

- It must follow the design system
- It must be done using Figma
- It must present the workflow in different views

## Motivation 🔦

This is important for the team to know how this views are going to be and how the doctor workflow requirements are going to be represented on the layout.

**Comment by rulo-code** [comment]
The issue has been resolve
We can see the user role flow in the following link
[Go notion](https://www.notion.so/Doctor-1c811f54388046aa83d46564226a4516)

In addition, we can view the figma prototype
[Mobile](https://www.figma.com/proto/xRZYYfOfWSGVr0J1IDDZsC/Kaizen?node-id=551%3A20976&scaling=min-zoom)
[Destock](https://www.figma.com/proto/xRZYYfOfWSGVr0J1IDDZsC/Kaizen?node-id=545%3A9343&scaling=min-zoom)
