### ISSUE TITLE
SSKW - Design Users roles workflow through the app

### ISSUE THREAD

**Issue by omarefg** [Sphinx-Society/kaizen-web-client#55]
## Checklist ✅

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/Sphinx-Society/kaizen-backend) of this repository and believe that this is not a duplicate.

## Summary 💡

This views will allow the development team to know what to develop following the design system.

## Requirements 🌈

- It must follow the design system
- It must be done using Figma
- It must present the workflow in different views

## Motivation 🔦

This is important for the team to know how this views are going to be and how the bacteriologist workflow requirements are going to be represented on the layout.

**Comment by rulo-code** [comment]
All roles have been design.

- [Admin destock](https://www.figma.com/proto/xRZYYfOfWSGVr0J1IDDZsC/Kaizen?node-id=541%3A5739&scaling=min-zoom)

- [Admin mobile](https://www.figma.com/proto/xRZYYfOfWSGVr0J1IDDZsC/Kaizen?node-id=215%3A622&scaling=min-zoom)
- [Bacteriologist destock](https://www.figma.com/proto/xRZYYfOfWSGVr0J1IDDZsC/Kaizen?node-id=710%3A1&scaling=min-zoom)
- [Bacteriologist mobile](https://www.figma.com/proto/xRZYYfOfWSGVr0J1IDDZsC/Kaizen?node-id=444%3A3724&scaling=min-zoom)
- [Doctor destock](https://www.figma.com/proto/xRZYYfOfWSGVr0J1IDDZsC/Kaizen?node-id=763%3A9244&scaling=min-zoom)
- [Doctor mobile](https://www.figma.com/proto/xRZYYfOfWSGVr0J1IDDZsC/Kaizen?node-id=551%3A20976&scaling=min-zoom)
- [Patient destock](https://www.figma.com/proto/xRZYYfOfWSGVr0J1IDDZsC/Kaizen?node-id=773%3A7920&scaling=min-zoom)
- [Patient mobile](https://www.figma.com/proto/xRZYYfOfWSGVr0J1IDDZsC/Kaizen?node-id=773%3A7421&scaling=min-zoom)
